### ISSUE TITLE
docker ci refactoring

### ISSUE THREAD

**Issue by alessandro-modolo** [overit-official/tomcat-redis-manager#46]
why not take the opportunity to review the pipeline and take advantage of these actions:

setup-buildx-action: to do the setup of buildx
metadata-action: to extract image version info
build-push-action: to do the push to dockerhub

here is a draft of the revised pipeline (obviously to be validated)

```
name: Docker CI

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  mvn-test:
    name: Maven Compile, Unit and Integration Tests
    runs-on: ubuntu-latest
    strategy:
        matrix:
            redis-version: [6, 7]
    steps:
    
    - id: checkout_code
      name: Checkout to source code
      uses: actions/checkout@v4
      
    - id: jdk_setup
      name: Set up JDK 17 for the tests
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - id: redis_setup
      name: Start Redis for the integration tests
      uses: supercharge/redis-github-action@1.8.0
      with:
        redis-version: ${{ matrix.redis-version }}
        
    - id: mvn_test
      name: Maven test
      run: mvn -B test

  docker-build-push:
    name: Build and Push Docker tags
    runs-on: ubuntu-latest
    needs: mvn-test
    outputs:
        release_version: ${{ steps.docker_build_push.outputs.release_version }}
    steps:

    - id: checkout_code
      name: Checkout code
      uses: actions/checkout@v4

    # Add support for more platforms with QEMU (optional)
    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - id: login_docker_hub
      name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
          images: |
              ${{ secrets.DOCKERHUB_ORGANIZATION }}/tomcat-redis-manager
          tags: |
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
              type=semver,pattern={{major}}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  github-release:
    name: Create Git Release
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
    
      - id: checkout_code
        name: Checkout code
        uses: actions/checkout@v4

      - id: jdk_setup
        name: Set up JDK 17 for the tests
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
                
      - id: mvn_package
        name: Maven package
        run: mvn package -DskipTests  
        
      - id: github_release
        name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          tag_name: ${{ github.ref }}
          release_name: ${{ needs.docker-build-push.outputs.release_version }}
          draft: false
          prerelease: false
          files: |
            LICENSE
            target/*-shaded.jar  
```
